### ISSUE TITLE
Client ID in requests wiki

### ISSUE THREAD

**Issue by BillSobel** [Ericmas001/Tuya-Api-Tools#1]
Eric, quick question.  Did you partially obfuscate the clientId in the Tuya requests wiki page?  The client id in you examples seems to have two digits swapped and wanted to confirm you intentionally did that thinking it was private info (that clientid is the Tuya clientid, not the end users) or if Tuya actually has two VERY close but different clientids in use.  Thanks!

**Comment by Ericmas001** [comment]
Yes, I probably did. I remember swapping numbers on a lot of things because I wasn't sure what was private and what was not :)

**Comment by BillSobel** [comment]
@Ericmas001 Thanks, just needed to verify.  Looks like you tested with the SDK (those keys are actually quasi available since you can download the SDK).  They are different keys from what the official app uses, but probably good for us doing this type of work.
